adapt: Decouple outer Adapt context from user program context This is a large commit with multiple intertwined fixes:
* Stop sharing Adapt inside user program context.
  The initial change here was to stop loading the already executing
  version of Adapt into the user program context (deleting
  VmContext.loadSelfMod), thus creating a new copy of Adapt and all
  its objects inside of the context. That change then made the rest
  of the changes necessary.

* Fix broken AdaptContext implementation.
  Without sharing Adapt, the user context created its own copy of
  AdaptContext that the outer context couldn't access. Change
  implementation to use a getAdaptContext method on global instead of a
  file-scope variable. Also, do not populate getAdaptContext except when
  running inside the user context. This ensures that we don't
  inadvertently accumulate garbage in the outer global AdaptContext.
  Exception: for unit testing, added mockAdaptContext and also added
  a separately loadable .js file that creates a mock AdaptContext for
  use by mocha --register.

* Create projectExec.
  Rather than put more project-specific details into context.ts, pull
  AdaptContext and other project-related items into projectExec.ts,
  leaving context.ts to focus just on compiling & executing. This also
  pulls some of the low-level exec interactions out of deployAndBuild,
  simplifying that code a bit. projectExec creates a new AdaptContext,
  runs the user program and returns the AdaptContext so that the caller
  can explicitly use the context rather than implicitly hoping that
  getStacks and others are getting data from the right place.

* "Getters" of AdaptContext need context data passed to them.
  Since projectExec passes back the AdaptContext and it's not available
  as a global in the outer context, all the "getters" that operate
  on data in AdaptContext now have to be passed an AdaptContext (or
  data from within the AdaptContext).
  As part of that change, removed setting up plugin config from
  Deployment (why was it there in the first place?) and stopped exposing
  PluginConfig as part of the plugin external API.

* Add inner copy of Adapt to AdaptContext.
  This allows the outer Adapt to call the inner Adapt's methods to
  complete the build/deploy process with a consistent set of (the inner
  context) Adapt objects.

* Use inner copy of Adapt in buildAndDeploy.
  Change buildAndDeploy to call the inner context's build, serializeDom,
  and reanimateDom. There will probably be a couple of similar changes
  to use the inner context's functions for observers and plugins.

* Reanimate DOM after build.
  To have the greatest probability of finding the objects that need to
  be reanimated, reanimate needs for the Components to be constucted. So
  delay call to reanimateDom until after build.

* Implement require.cache inside user context.
  Reanimate uses require.cache, which wasn't available inside the user
  context. Adding that obviated the need for the VmModule cache, so just
  replaced one with the other.

* require.resolve fixes
  The error message thrown by require.resolve had the wrong info in it
  (should be request, not path) and was different behavior than Node's
  error. Mimic Node's.

* Stop polluting outer context's require.cache.
  There was an explicit set of the outer context's require.cache with
  modules from the inner context. That's broken. Stop it.

* Stop passing outer context Javascript globals into inner context.
  Passing Javascript-language-defined globals like TypeError into the
  inner context is broken. One reason it's broken is because if V8
  itself throws a TypeError inside the inner context, it will throw that
  context's unique TypeError object, but any code in the context will
  use the global (outer context's) TypeError, meaning that instancof
  checks will fail inside the inner context. Only pass Node-specific
  globals that V8 doesn't create into the inner context.

* Use vm.runInContext instead of vm.Script.runInContext
  Changed as part of debugging, but really just a slight simplification
  of the code that wasn't absolutely necessary.

* createDeployment test fixes
  simplePackageJson was missing the required typescript dependency.
  Moved creation of the project into before() so the tests can be run
  independently.
  Ensure stdout mock .stop is called if tests fail.